### ISSUE TITLE
How to use ExclusiveStartKey?

### ISSUE THREAD

**Issue by mave99a** [noppoMan/npdynamodb#32]
I used limit() in the query and it works as expected, and I got LastEvaluatedKey from the result. 

The question is, how to pass this as ExclusiveStartKey in the next query?  Thanks!

**Comment by noppoMan** [comment]
@mave99a 
Thanks for using npdynamodb!

You can pass LastEvaluatedKey to exclusiveStartKey method in feature method callback.
Here is example.

### For Query Builder

``` js
npd().table("foo").limit(10).feature(function(f){
  f.exclusiveStartKey(LastEvaluatedKey);
}).then(function(results){
  console.log(results);
});
```

### For ORM

``` js
Model.query(function(qb){
  qb.limit(10);
  qb.feature(function(f){
   f.exclusiveStartKey(LastEvaluatedKey);
  });
}).then(function(results){
  console.log(results);
});
```

Feature api has  grouped non required parameters for each operations of Dynamodb api version 2012-08-10.
Other methods that are grouped in feature is here.
https://github.com/noppoMan/npdynamodb#feature-methods-2012-08-10

Sorry for your confusing but I'm considering to make offset method to pass LastEvaluatedKey that is like sql interface.

Thanks!

**Comment by mave99a** [comment]
Thanks a lot! It worked perfectly!

**Comment by mave99a** [comment]
Close this issue.
