### ISSUE TITLE
Dynastyjs

### ISSUE THREAD

**Issue by mave99a** [noppoMan/npdynamodb#35]
Hi Yuki, great project! Makes the dynamoDB much easier to use. I happen find a similar project today, wondering if you happen evaluated it before? 

http://dynastyjs.com/

**Comment by noppoMan** [comment]
Hi Robert, I've not seen before that.
I tried to use https://github.com/ryanfitz/vogels and https://github.com/tglines/dynasaur. They are good libraries but didn't fit.
Actually I got Inspiration from [Bookshelf.js](http://bookshelfjs.org/) and [knex.js](http://knexjs.org/) which are ORM and QueryBuilder for RDBMS in Node.js.  They are awesome.

DynamoDB has a lot of practical functions but SDK always disturb us with many parameters too hard to remember.
So I started to make npdynamodb to handle it Intuitively without restrictive SDK interface.
My Answer is using Sql and ActiveRecord like Interface is intuitive and basic for recent web developers.
Of course Migrator and CLI are necessary to operate web service.

thanks!
