### ISSUE TITLE
whereIn not working

### ISSUE THREAD

**Issue by vinodhum** [noppoMan/npdynamodb#56]
InvalidParameterType: Expected params.RequestItems['tablename'].Keys[0]['EmployeeId'] to be a structure

below is what i was trying and I keep getting above error, i checked all the keys and table name everything is correct. but still keep getting above error.

 function (callback) {
        npd().table('tablename')
            .whereIn('EmployeeId', ['emp_id'])
            .then(function (data) {
                callback(null, data.toArray());
            })
    }

**Comment by noppoMan** [comment]
umm, I've never seen this error. Could you send me the table structure?(I'm thinking you may have RangeKey in the table)

**Comment by vinodhum** [comment]
Primary partition key	EmployeeId (String)
Primary sort key	-

I can do other operation like, query, put, where, destroy but failing on whereIn

**Comment by vinodhum** [comment]
hi any update on how to resolve it ?
